#!/usr/bin/env bash
# script to discover if hosts are on the network using ping.
# Script to ping 5 times

if [ "$#" -ne 1 ]; then
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    IP=$1
    ping -c 5 "$IP"
fi
